#!/bin/sh
set -e

install_tools() {
  read -p "Installing tools. Press Enter to continue..."
  sudo apt update -y
  sudo apt install -y wget jq liblz4-tool
  read -p "Done. Press Enter to continue..."
  clear
}

install_go() {
  read -p "Installing Go. Press Enter to continue..."
  ver="1.22.0"
  wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
  sudo rm -rf /usr/local/go
  sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
  rm "go$ver.linux-amd64.tar.gz"
  echo "export PATH=\$PATH:/usr/local/go/bin:\$HOME/go/bin" >> ~/.bash_profile
  source ~/.bash_profile
  go version
  read -p "Done. Press Enter to continue..."
  clear
}

install_story_geth() {
  read -p "Installing story-geth. Press Enter to continue..."
  wget -q https://story-geth-binaries.s3.us-west-1.amazonaws.com/geth-public/geth-linux-amd64-0.9.3-b224fdf.tar.gz
  tar -xzf geth-linux-amd64-0.9.3-b224fdf.tar.gz
  [ ! -d "$HOME/go/bin" ] && mkdir -p $HOME/go/bin
  cp geth-linux-amd64-0.9.3-b224fdf/geth $HOME/go/bin/story-geth
  read -p "Done. Press Enter to continue..."
  clear
}

install_story() {
  read -p "Installing story. Press Enter to continue..."
  wget -q https://story-geth-binaries.s3.us-west-1.amazonaws.com/story-public/story-linux-amd64-0.10.1-57567e5.tar.gz
  tar -xzf story-linux-amd64-0.10.1-57567e5.tar.gz
  cp story-linux-amd64-0.10.1-57567e5/story $HOME/go/bin/story
  read -p "Done. Press Enter to continue..."
  clear
}

init_iliad_network() {
  read -p "Initializing the iliad network. Press Enter to continue..."
  $HOME/go/bin/story init --network iliad
  read -p "Done. Press Enter to continue..."
  clear
}

create_and_run_story_geth_service() {
  read -p "Creating and running story-geth service. Press Enter to continue..."

  # Download the story-geth.service file
  wget -q https://raw.githubusercontent.com/apri-me/story-files/refs/heads/main/story-geth.service

  # Replace the placeholders with the actual values
  sudo sed -i "s|\${USER_NAME}|$USER|g; s|\${YOUR_HOME_DIR}|$HOME|g" story-geth.service

  # Move the file to the systemd directory
  sudo cp story-geth.service /etc/systemd/system/story-geth.service

  # Reload the systemd daemon, unmask the service, enable the service, restart the service and follow the logs
  sudo systemctl daemon-reload
  sudo systemctl unmask story-geth
  sudo systemctl enable story-geth
  read -p "Done. Press Enter to continue..."
  clear
}

create_and_run_story_consensus_service() {
  read -p "Creating and running story consensus service. Press Enter to continue..."

  # Download the story.service file
  sudo wget -q https://raw.githubusercontent.com/apri-me/story-files/refs/heads/main/story.service

  # Replace the placeholders with the actual values
  sudo sed -i "s|\${USER_NAME}|$USER|g; s|\${YOUR_HOME_DIR}|$HOME|g" story.service

  # Move the file to the systemd directory
  sudo cp story.service /etc/systemd/system/story.service

  # Reload the systemd daemon, unmask the service, enable the service, restart the service and follow the logs
  sudo systemctl daemon-reload
  sudo systemctl unmask story
  sudo systemctl enable story
  read -p "Done. Press Enter to continue..."
  clear
}

inform_status_command(){
  echo "You can check the status by running the following command:"
  echo "curl -s localhost:26657/status | jq"
}


start_one_liner() {
  cd
  mkdir temp_dumps
  cd temp_dumps/
  install_tools
  install_go
  install_story_geth
  install_story
  init_iliad_network
  create_and_run_story_geth_service
  create_and_run_story_consensus_service
  inform_status_command
  cd
  rm -rf temp_dumps/
}

start_one_liner
